name: '🚀 - Feature Request'
title: '🚀 - '
description: Suggest a feature for Taiga UI
labels: ['feature', 'state: need triage']

body:
  - type: dropdown
    id: affected-packages
    attributes:
      label: Which @taiga-ui/* package(s) are relevant/releated to the feature request?
      options:
        - core
        - calendar
        - config
        - error
        - exam
        - feedback
        - login
        - reset-password
        - settings
        - shared
        - shell
        - statistic
        - teaching-schedule
        - user-info
        - Don't known / other
      multiple: true

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: |
        Proposed solution.
        Alternatives considered.
    validations:
      required: true
